name: node-instance

on:
  push:
    branch: [main]

jobs: 
  bash:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run Node
        run: |
          cd backend; npm test
